=== ritesh9835/EmailServices/SendingEmailsWithWebMailInMVC/SendingEmailsWithWebMailInMVC/richtexteditor/core/jsml.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="jsml" targetNamespace="http://cutesoft.net/jsml" elementFormDefault="qualified" xmlns="http://cutesoft.net/jsml" xmlns:mstns="http://cutesoft.net/jsml" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="jsml-var">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^=]?[0-9a-zA-Z_${}]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="jsml-var-list">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^=]?[0-9a-zA-Z_${},]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="visibility">
		<xs:restriction base="xs:string">
			<xs:enumeration value="visible" />
			<xs:enumeration value="hidden" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="jsml-dock">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top" />
			<xs:enumeration value="left" />
			<xs:enumeration value="right" />
			<xs:enumeration value="bottom" />
			<xs:enumeration value="fill" />
			<xs:enumeration value="over" />
			<xs:enumeration value="flow" />
			<xs:enumeration value="none" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="content-flow">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left" />
			<xs:enumeration value="right" />
			<xs:enumeration value="bottomleft" />
			<xs:enumeration value="bottomright" />
			<xs:enumeration value="uptoleft" />
			<xs:enumeration value="downtoleft" />
			<xs:enumeration value="uptoright" />
			<xs:enumeration value="downtoright" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="flow-clear">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none" />
			<xs:enumeration value="both" />
			<xs:enumeration value="prev" />
			<xs:enumeration value="next" />
			<xs:enumeration value="follow" />
			<xs:enumeration value="newline" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="jsml-overflow">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none" />
			<xs:enumeration value="visible" />
			<xs:enumeration value="scroll" />
			<xs:enumeration value="default" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="zoom-mode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none" />
			<xs:enumeration value="both" />
			<xs:enumeration value="in" />
			<xs:enumeration value="out" />
			<xs:pattern value="(none)|(both)|(in)|(out)|([0-9%\.]+)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="vertical-align">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top" />
			<xs:enumeration value="middle" />
			<xs:enumeration value="bottom" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="horizontal-align">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left" />
			<xs:enumeration value="center" />
			<xs:enumeration value="right" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="text-mode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="singleline" />
			<xs:enumeration value="multipleline" />
			<xs:enumeration value="password" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="jsml-xmldata" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:any />
		</xs:choice>
		<xs:attribute name="rawhtml" type="xs:boolean" />
	</xs:complexType>
	<xs:complexType name="jsml-constructor">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="arguments" type="jsml-var-list" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-initialize">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-method">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="name" type="jsml-var" use="required" />
				<xs:attribute name="arguments" type="jsml-var-list" />
				<xs:attribute name="overrideas" type="jsml-var" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-attach">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="name" type="jsml-var-list" use="required" />
				<xs:attribute name="arguments" type="jsml-var-list" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-propgetset">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="arguments" type="jsml-var-list" />
				<xs:attribute name="overrideas" type="jsml-var" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="list-item">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="value" type="xs:string" />
				<xs:attribute name="text" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-jsml">
		<xs:attribute name="jsml-enable" type="xs:boolean" />
		<xs:attribute name="jsml-append" type="xs:boolean" />
		<xs:attribute name="jsml-class" type="jsml-var" />
		<xs:attribute name="jsml-base" type="jsml-var" />
		<xs:attribute name="jsml-local" type="jsml-var" />
		<xs:attribute name="jsml-member" type="jsml-var" />
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="var" type="jsml-var" />
		<xs:attribute name="vars" type="jsml-var-list" />
		<xs:anyAttribute />
	</xs:complexType>
	<xs:complexType name="jsml-control">
		<xs:complexContent>
			<xs:extension base="jsml-jsml">
				<xs:attribute name="parent" type="xs:string" />
				<xs:attribute name="top" type="xs:string" />
				<xs:attribute name="left" type="xs:string" />
				<xs:attribute name="right" type="xs:string" />
				<xs:attribute name="bottom" type="xs:string" />
				<xs:attribute name="width" type="xs:string" />
				<xs:attribute name="height" type="xs:string" />
				<xs:attribute name="min_width" type="xs:string" />
				<xs:attribute name="min_height" type="xs:string" />
				<xs:attribute name="max_width" type="xs:string" />
				<xs:attribute name="max_height" type="xs:string" />
				<xs:attribute name="unselectable" type="xs:boolean" />
				<xs:attribute name="visible" type="xs:boolean" />
				<xs:attribute name="visibility" type="visibility" />
				<xs:attribute name="disabled" type="xs:boolean" />
				<xs:attribute name="dock" type="jsml-dock" />
				<xs:attribute name="flow_clear" type="flow-clear"/>
				<xs:attribute name="margin" type="xs:string" />
				<xs:attribute name="border_width" type="xs:string" />
				<xs:attribute name="border_style" type="xs:string" />
				<xs:attribute name="border_color" type="xs:string" />
				<xs:attribute name="back_color" type="xs:string" />
				<xs:attribute name="text_color" type="xs:string" />
				<xs:attribute name="background" type="xs:string" />
				<xs:attribute name="text" type="xs:string" />
				<xs:attribute name="tooltip" type="xs:string" />
				<xs:attribute name="font" type="xs:string" />
				<xs:attribute name="font_size" type="xs:string" />
				<xs:attribute name="cursor" type="xs:string" />
				<xs:attribute name="opacity" type="xs:string" />
				<xs:attribute name="css_class" type="xs:string" />
				<xs:attribute name="css_text" type="xs:string" />
				<xs:attribute name="overflow" type="jsml-overflow"/>
				<xs:attribute name="overflow_x" type="jsml-overflow"/>
				<xs:attribute name="overflow_y" type="jsml-overflow"/>
				<xs:attribute name="horizontal_align" type="horizontal-align" />
				<xs:attribute name="vertical_align" type="vertical-align" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-simplecontrol">
		<xs:complexContent>
			<xs:extension base="jsml-control">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:group ref="class-member-group" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-complexcontrol">
		<xs:complexContent>
			<xs:extension base="jsml-control">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:group ref="class-member-group" />
					<xs:group ref="sub-element-group" />
				</xs:choice>
				<xs:attribute name="padding" type="xs:string" />
				<!--<xs:attribute name="zoom" type="zoom-mode" />-->
				<xs:attribute name="content_flow" type="content-flow" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="jsml-panel">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-groupbox">
		<xs:complexContent>
			<xs:extension base="jsml-panel">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!--<xs:complexType name="jsml-grid">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="row" type="jsml-row" />
				</xs:choice>
				<xs:attribute name="cell_border_width" type="xs:string" />
				<xs:attribute name="cell_border_style" type="xs:string" />
				<xs:attribute name="cell_border_color" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-row">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="cell" type="jsml-cell" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-cell">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>-->

	<xs:complexType name="jsml-jsmlelement">
		<xs:complexContent>
			<xs:extension base="jsml-simplecontrol">
				<xs:attribute name="zoom" type="zoom-mode" />
				<xs:attribute name="padding" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-htmlcontrol">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="html" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-image">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="src" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-label">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="text_align" type="horizontal-align" />
				<xs:attribute name="word_wrap" type="xs:boolean" />
				<xs:attribute name="font_size" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-textbox">
		<xs:complexContent>
			<xs:extension base="jsml-simplecontrol">
				<xs:attribute name="text_mode" type="text-mode" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-checkbox">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="checked" type="xs:boolean" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-dropdown">
		<xs:complexContent>
			<xs:extension base="jsml-simplecontrol">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="listitem" type="list-item"/>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:group name="class-member-group">
		<xs:choice>
			<xs:element name="jsml-ref">
				<xs:complexType>
					<xs:attribute name="jsml-enable" type="xs:boolean" />
					<xs:attribute name="name" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="constructor" type="jsml-constructor" />
			<xs:element name="initialize" type="jsml-initialize" />
			<xs:element name="method" type="jsml-method" />
			<xs:element name="attach" type="jsml-attach" />
			<xs:element name="xmldata" type="jsml-xmldata" />
			<xs:element name="property">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="get" type="jsml-propgetset" minOccurs="1" maxOccurs="1" />
						<xs:element name="set" type="jsml-propgetset" minOccurs="0" maxOccurs="1" />
					</xs:sequence>
					<xs:attribute name="name" type="jsml-var" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="sub-element-group">
		<xs:choice>
			<xs:element name="htmlcontrol" type="jsml-htmlcontrol" />
			<xs:element name="button" type="jsml-simplecontrol" />
			<xs:element name="image" type="jsml-image" />
			<xs:element name="label" type="jsml-label" />
			<xs:element name="textbox" type="jsml-textbox" />
			<xs:element name="dropdown" type="jsml-dropdown" />
			<xs:element name="checkbox" type="jsml-checkbox" />
			<xs:element name="panel" type="jsml-panel" />
			<xs:element name="groupbox" type="jsml-groupbox" />
			<!--<xs:element name="grid" type="jsml-grid" />-->
			<xs:element name="object">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="jsml-complexcontrol">
							<xs:attribute name="jsml-base" type="jsml-var" use="required" />
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="jsml-comment">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:any processContents="skip" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="jsml-block">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:group ref="sub-element-group" />
					</xs:choice>
					<xs:attribute name="jsml-enable" type="xs:boolean" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:element name="jsml">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group ref="sub-element-group" />
				<xs:element name="execute">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="jsml-enable" type="xs:boolean" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="include">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="jsml-enable" type="xs:boolean" />
								<xs:attribute name="src"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="jsml-def">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:group ref="class-member-group" />
							<xs:group ref="sub-element-group" />
						</xs:choice>
						<xs:attribute name="jsml-enable" type="xs:boolean" />
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ritesh9835/EmailServices/SendingEmailsWithWebMailInMVC/SendingEmailsWithWebMailInMVC/richtexteditor/dialogs/colorpicker.xml
<?xml version="1.0" encoding="utf-8" ?>
<jsml xmlns="http://cutesoft.net/jsml"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cutesoft.net/jsml ../core/jsml.xsd">

	<panel jsml-class="colorpickericon" dock="flow" width="16" height="16" margin="2" border_color="transparent" border_width="1" cursor="pointer">
		<panel jsml-member="inner" dock="fill" border_color="gray" border_width="1" back_color="black" />
	</panel>
	
	<panel jsml-class="colorpickeritem" dock="flow" width="16" height="16" margin="2" border_color="transparent" border_width="1" cursor="pointer">
		<panel jsml-member="inner" dock="fill" border_color="gray" border_width="1" />
		<property name="value">
			<get>
				return self.inner.get_back_color();
			</get>
			<set>
				self.inner.set_back_color(value);
			</set>
		</property>
		<method name="setup_preview" arguments="html,cmd">
			self._previewhtml=html;
			self._previewcmd=cmd;
			self._previewstyle=(cmd=="forecolor"?"color":"background-color");
		</method>
		<attach name="mousehover" arguments="je,e">
			<![CDATA[
			self.set_border_color('orange');
			
			self._hovered=true;
			if(!self._previewhtml)return;
			if(self.currentdialog&&self.currentdialog.get_visible())
				return;
			
			var newoption={control:self,floatMode:'b-r',stopToggle:true,stopOverlay:true};
			newoption.buttonClick=function()
			{
				self.invoke_event("click");
			}
			var dialog=jsml.class_create_instance("floatbox");
			var htmlc=jsml.class_create_instance("htmlcontrol");
			htmlc.set_html("<pre style='margin:0px;padding:0px;font-weight:bold;'>Preview for color : "+self.get_value()+"</pre><pre style='padding:5px;"+self._previewstyle+":"+self.get_value()+"'>"+self._previewhtml+"</pre>");
			htmlc.set_dock("fill");
			var gbr=jsml.get_body_rect();
			htmlc.set_max_width(Math.floor(gbr.width*0.6));
			htmlc.set_max_height(Math.floor(gbr.height*0.3));
			htmlc.set_vertical_align("middle");
			dialog.append_child(htmlc);
			dialog.set_width(240);
			dialog.set_padding(12);
			dialog._estyle.zIndex=editor._config.dialog_zindex;
			dialog.show(newoption);
			self.currentdialog=dialog;
			]]>
		</attach>
		<attach name="mouseleave">
			<![CDATA[
			self.set_border_color('transparent');
			
			self._hovered=false;
			self.setDelegateTimeout(function()
			{
				if(self._hovered)return;
				if(self.currentdialog&&self.currentdialog.get_visible())
				{
					self.currentdialog.close();
				}
			},11);
			]]>
		</attach>
		<attach name="click">
			dialog.close();
			option.setcolor(self.get_value());
		</attach>
	</panel>
	
	

	<panel jsml-class="colorpickerpanel" dock="fill" padding="6" width="186" overflow="visible">

		<panel jsml-base="panelbutton" dock="top" margin="2,2,2,2" padding="0,3,0,3">
			<panel jsml-base="colorpickericon" dock="left"/>
			<label dock="fill" text="@automatic" cursor="pointer" vertical_align="middle" horizontal_align="center"/>
			<attach name="click">
				dialog.close();
				option.setcolor("");
			</attach>
		</panel>
		<panel jsml-base="panelbutton" dock="bottom" margin="2,2,2,2" padding="0,3,0,3">
			<panel jsml-base="colorpickericon" dock="left"/>
			<label dock="fill" text="@MoreColors" cursor="pointer" vertical_align="middle" horizontal_align="center" />
			<attach name="click">
				<![CDATA[
				dialog.close();
				var newoption={}
				newoption.width=510;
				newoption.height=460;
				newoption.callback=function(val)
				{
					if(!val)return;
					option.setcolor(val);
				}
				editor.ShowXmlDialog("{folder}server/colorpicker.xml",newoption);
				]]>
			</attach>
		</panel>
		<panel jsml-local="arraypanel" padding="6" dock="fill" overflow="visible">
		</panel>

		<initialize>
			<![CDATA[
			var type=String(option.command).toLowerCase();
			var arr=editor._config.colorpicker_othercolor;
			switch(type)
			{
				case "forecolor":
					arr=editor._config.colorpicker_forecolor;
					if(option.preview&&!editor._config.preview_disabletooltip&&!editor._config.preview_disableforecolor)
					{
						self._previewcmd="forecolor";
						self._previewhtml=editor.GetRangePreviewHTML("forecolor");
					}
					break;
				case "backcolor":
					arr=editor._config.colorpicker_backcolor;
					if(option.preview&&!editor._config.preview_disabletooltip&&!editor._config.preview_disablebackcolor)
					{
						self._previewcmd="backcolor";
						self._previewhtml=editor.GetRangePreviewHTML("backcolor");
					}
					break;
			}
			for(var i=0;i<arr.length;i++)
			{
				var item=jsml.class_create_instance("colorpickeritem");
				if(self._previewhtml)
					item.setup_preview(self._previewhtml,self._previewcmd);
				else
					item.set_tooltip(arr[i])
				item.set_value(arr[i]);
				arraypanel.append_child(item);
			}
			]]>
		</initialize>
		
		<attach name="keydown" arguments="je,e">
			if(e.keyCode==27)dialog.close();
		</attach>
	</panel>

	<panel jsml-base="colorpickerpanel" />


</jsml>

=== ritesh9835/EmailServices/SendingEmailsWithWebMailInMVC/SendingEmailsWithWebMailInMVC/richtexteditor/dialogs/menu_context_simple.xml
<?xml version="1.0" encoding="utf-8" ?>
<jsml xmlns="http://cutesoft.net/jsml"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cutesoft.net/jsml ../core/jsml.xsd">

	<panel jsml-class="menu_context_table" jsml-base="floatmenu">

		<panel jsml-base="rtemenuitem" command="mergecells" imagename="mrgcell" htmlcode="@MERGECELLS" />
		<panel jsml-base="rtemenuitem" command="splitcells" imagename="spltcell" htmlcode="@SPLITCELLS" />
		<panel jsml-base="rtemenuspliter" />
		<panel jsml-base="rtemenuitem" command="deleterow" htmlcode="@DELETEROW" imagename="delrow"  />
		<panel jsml-base="rtemenuitem" command="deletecolumn" htmlcode="@DELETECOLUMN" imagename="delcol"  />
		<panel jsml-base="rtemenuitem" command="insertrowtop" htmlcode="@INSERTROWTOP" imagename="insrow_t"  />
		<panel jsml-base="rtemenuitem" command="insertrowbottom" htmlcode="@INSERTROWBOTTOM" imagename="insrow_b"  />
		<panel jsml-base="rtemenuspliter" />
		<panel jsml-base="rtemenuitem" command="insertcolumnleft" htmlcode="@INSERTCOLUMNLEFT" imagename="inscol_l"  />
		<panel jsml-base="rtemenuitem" command="insertcolumnright" htmlcode="@INSERTCOLUMNRIGHT" imagename="inscol_r" />

	</panel>

	<panel jsml-class="menu_context_taglist" jsml-base="floatmenu">
		<initialize>
			<![CDATA[
			var node=editor.GetSelectionRoot();
			for(;node&&node.GetNameLower()!="body";node=node.GetParent())
			{
				if(node.nodeType!=1)continue;
				
				var item=self.createitem(node);
				self.append_child(item);
			}
			]]>
		</initialize>
		<method name="createitem" arguments="node">
			<![CDATA[
			var item=jsml.class_create_instance("rtemenuitem");
			item.set_arrow(true);
			item.set_xmlfile("menu_tagitem.xml");
			item._floatboxClass="floatmenu";
			item.initoption=function(newoption)
			{
				newoption.node=node;
				newoption.buttonClick=function()
				{
					item.invoke_event("click");
				}
			}
			item.attach_event("click",function()
			{
				editor.ShowPropertiesDialog(node);
			});
			item.set_text(node.GetName());
			return item;
			]]>
		</method>
	</panel>


	<panel jsml-base="rtemenuitem" command="mergecells" imagename="mrgcell" htmlcode="@MERGECELLS">
		<initialize>
			if(!editor.CanExecCommand("mergecells"))self.set_visible(false);
		</initialize>
	</panel>

	<panel jsml-base="rtemenuitem" command="selectall" imagename="selectall" htmlcode="@SELECTALL" />

	<panel jsml-base="rtemenuitem" command="undo" imagename="undo" htmlcode="@UNDO" />

	<panel jsml-base="rtemenuspliter" />

	<panel jsml-base="rtemenuitem" command="cut" imagename="cut" htmlcode="@CUT">
		<attach name="mousehover">self._ResetFCButton();</attach>
	</panel>
	<panel jsml-base="rtemenuitem" command="copy" imagename="copy" htmlcode="@COPY">
		<attach name="mousehover">self._ResetFCButton();</attach>
	</panel>

	<panel jsml-base="rtemenuitem" command="delete" imagename="delete" htmlcode="@DELETE" />

	<panel jsml-base="rtemenuspliter" />



	<panel jsml-base="rtemenuopener" menuclass="menu_context_taglist" htmlcode="@TAGLIST">
		<initialize>
			<![CDATA[
			var node=editor.GetSelectionRoot();
			var count=0;
			for(;node&&node.GetNameLower()!="body";node=node.GetParent())
			{
				if(node.nodeType==1)count++;
			}
			if(count==0)self.set_disabled(true);
			]]>
		</initialize>
	</panel>

	<panel jsml-base="rtemenuopener" menuclass="menu_context_table" htmlcode="@TABLE">
		<initialize>
			var table=editor.IsIncludedByTag("table");
			if(table==null)return self.set_visible(false);
		</initialize>
	</panel>

	<panel jsml-base="rtemenuitem" htmlcode="@IMAGEEDITOR" imagename="imageeditor">
		<initialize>
			<![CDATA[
			var node=editor.GetSelectionRoot();
			if(!node||node.GetNameLower()!="img")self.set_visible(false);
			self.set_disabled(true);
			editor.FindStorage(["Gallery","Image"],node.GetAttribute("src"),function(storage,fileitem)
			{
				if(!storage)return;
				self.imgnode=node;
				self.storage=storage;
				self.fileitem=fileitem;
				self.set_disabled(false);
			});
			]]>
		</initialize>
		<attach name="click">
			if(!self.storage)return;
			editor.ShowImageEditor(self.imgnode,self.storage,self.fileitem);
		</attach>
	</panel>

	<panel jsml-base="rtemenuitem" htmlcode="@INSERTIMAGEMAP" imagename="imagemap">
		<initialize>
			<![CDATA[
				var node=editor.GetSelectionRoot();
				if(!node||node.GetNameLower()!="img")self.set_visible(false);
				self.imgnode=node;
				]]>
		</initialize>
		<attach name="click">
			editor.ExecInsertImageMap(null,self.imgnode);
		</attach>
	</panel>


	<panel jsml-base="rtemenuitem" imagename="link" htmlcode="@EDIT| |@LINK">
		<initialize>
			var link=editor.IsIncludedByTag("a");
			if(link==null)return self.set_visible(false);
		</initialize>
		<attach name="click">
			var link=editor.IsIncludedByTag("a");
			if(link)editor.ShowPropertiesDialog(link);
		</attach>
	</panel>
	<panel jsml-base="rtemenuitem" imagename="unlink" htmlcode="@REMOVE| |@LINK">
		<initialize>
			var link=editor.IsIncludedByTag("a");
			if(link==null)return self.set_visible(false);
		</initialize>
		<attach name="click">
			var link=editor.IsIncludedByTag("a");
			if(link)link.RemoveNode(false);
		</attach>
	</panel>
	
	<panel jsml-base="rtemenuitem" htmlcode="@STYLES" imagename="properties">
		<initialize>
			<![CDATA[
				var node=editor.GetSelectionRoot();
				if(!node||!node.IsControl())
				{
					self.set_visible(false);
					return;
				}
				self.set_arrow(true);
				self.set_xmlfile("menu_styles.xml");
				self._floatboxClass="floatmenu";
				self.initoption=function(newoption)
				{
					newoption.node=node;
					newoption.buttonClick=function()
					{
						self.invoke_event("click");
					}
				}
				]]>
		</initialize>
		<attach name="click">
			editor.ShowPropertiesDialog(editor.GetSelectionRoot(),{styletab:"text"})
		</attach>
	</panel>
	<panel jsml-base="rtemenuitem" htmlcode="@PROPERTIES" imagename="properties">
		<initialize>
			var node=editor.GetSelectionRoot();
			if(!node||!node.IsControl())self.set_visible(false);
		</initialize>
		<attach name="click">
			editor.ShowPropertiesDialog(editor.GetSelectionRoot())
		</attach>
	</panel>


</jsml>

=== ritesh9835/EmailServices/SendingEmailsWithWebMailInMVC/SendingEmailsWithWebMailInMVC/richtexteditor/dialogs/insertlink_dropdown.xml
<?xml version="1.0" encoding="utf-8" ?>
<jsml xmlns="http://cutesoft.net/jsml"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cutesoft.net/jsml ../core/jsml.xsd">


	<panel jsml-class="insertlinkdropdown_dialog" dock="fill" overflow="visible">
		<groupbox text="@internallink" dock="top" overflow="visible" margin="3">
			<panel width="280" height="210" overflow="scroll">
				<htmlcontrol jsml-local="container" margin="2" padding="4" overflow="visible">
				</htmlcontrol>
			</panel>
		</groupbox>
		<initialize>
			<![CDATA[
			editor.LoadLinks(function(group)
			{
				self.loadgroupcontent(group,container._content);
			});
			]]>
		</initialize>
		<jsml-ref name="linktree"/>
		<attach name="clicklink" arguments="je,link">
			<![CDATA[
			var tag=new $rte.LinkElement("a");
			tag.SetAttribute("href",link.href);
			if(editor.GetSelectionType()=="Point")
			{
				//TIPS:use link.text instead of the url
				//tag.SetInnerText(link.text);
				tag.SetInnerText(link.href);
				editor.InsertNode(tag);
				editor.SelectContent(tag);
			}
			else
			{
				if(editor.SurroundNode(tag))
				{
					editor.RemoveInnerLink(tag);
					editor.SelectContent(tag);
				}
			}
			dialog.close();
			]]>
		</attach>
	</panel>

	<panel jsml-base="insertlinkdropdown_dialog" />


</jsml>

=== ritesh9835/EmailServices/SendingEmailsWithWebMailInMVC/SendingEmailsWithWebMailInMVC/richtexteditor/dialogs/phone_text.xml
<?xml version="1.0" encoding="utf-8" ?>
<jsml xmlns="http://cutesoft.net/jsml"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cutesoft.net/jsml ../core/jsml.xsd">

	<panel jsml-class="phonetextdialog" dock="fill" overflow="visible" margin="0" padding="15">
		<panel dock="top" height="30">
			<button dock="left" width="60" text="@ok">
				<attach name="click">
					editor.AppendHTML(pastearea.get_text());
					dialog.close();
				</attach>
			</button>
			<button dock="left" width="60" text="@close" margin="0,0,0,5">
				<attach name="click">
					dialog.close();
				</attach>
			</button>
		</panel>
		<textbox jsml-local="pastearea" dock="fill" text_mode="multipleline" margin="5,0,0,0"></textbox>
	</panel>

	<panel jsml-base="phonetextdialog">
	</panel>

</jsml>
