=== ritesh9835/EmailServices/SendingEmailsWithWebMailInMVC/SendingEmailsWithWebMailInMVC/richtexteditor/core/jsml.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="jsml" targetNamespace="http://cutesoft.net/jsml" elementFormDefault="qualified" xmlns="http://cutesoft.net/jsml" xmlns:mstns="http://cutesoft.net/jsml" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="jsml-var">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^=]?[0-9a-zA-Z_${}]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="jsml-var-list">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^=]?[0-9a-zA-Z_${},]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="visibility">
		<xs:restriction base="xs:string">
			<xs:enumeration value="visible" />
			<xs:enumeration value="hidden" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="jsml-dock">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top" />
			<xs:enumeration value="left" />
			<xs:enumeration value="right" />
			<xs:enumeration value="bottom" />
			<xs:enumeration value="fill" />
			<xs:enumeration value="over" />
			<xs:enumeration value="flow" />
			<xs:enumeration value="none" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="content-flow">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left" />
			<xs:enumeration value="right" />
			<xs:enumeration value="bottomleft" />
			<xs:enumeration value="bottomright" />
			<xs:enumeration value="uptoleft" />
			<xs:enumeration value="downtoleft" />
			<xs:enumeration value="uptoright" />
			<xs:enumeration value="downtoright" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="flow-clear">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none" />
			<xs:enumeration value="both" />
			<xs:enumeration value="prev" />
			<xs:enumeration value="next" />
			<xs:enumeration value="follow" />
			<xs:enumeration value="newline" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="jsml-overflow">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none" />
			<xs:enumeration value="visible" />
			<xs:enumeration value="scroll" />
			<xs:enumeration value="default" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="zoom-mode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none" />
			<xs:enumeration value="both" />
			<xs:enumeration value="in" />
			<xs:enumeration value="out" />
			<xs:pattern value="(none)|(both)|(in)|(out)|([0-9%\.]+)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="vertical-align">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top" />
			<xs:enumeration value="middle" />
			<xs:enumeration value="bottom" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="horizontal-align">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left" />
			<xs:enumeration value="center" />
			<xs:enumeration value="right" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="text-mode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="singleline" />
			<xs:enumeration value="multipleline" />
			<xs:enumeration value="password" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="jsml-xmldata" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:any />
		</xs:choice>
		<xs:attribute name="rawhtml" type="xs:boolean" />
	</xs:complexType>
	<xs:complexType name="jsml-constructor">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="arguments" type="jsml-var-list" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-initialize">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-method">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="name" type="jsml-var" use="required" />
				<xs:attribute name="arguments" type="jsml-var-list" />
				<xs:attribute name="overrideas" type="jsml-var" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-attach">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="name" type="jsml-var-list" use="required" />
				<xs:attribute name="arguments" type="jsml-var-list" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-propgetset">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="arguments" type="jsml-var-list" />
				<xs:attribute name="overrideas" type="jsml-var" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="list-item">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="value" type="xs:string" />
				<xs:attribute name="text" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-jsml">
		<xs:attribute name="jsml-enable" type="xs:boolean" />
		<xs:attribute name="jsml-append" type="xs:boolean" />
		<xs:attribute name="jsml-class" type="jsml-var" />
		<xs:attribute name="jsml-base" type="jsml-var" />
		<xs:attribute name="jsml-local" type="jsml-var" />
		<xs:attribute name="jsml-member" type="jsml-var" />
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="var" type="jsml-var" />
		<xs:attribute name="vars" type="jsml-var-list" />
		<xs:anyAttribute />
	</xs:complexType>
	<xs:complexType name="jsml-control">
		<xs:complexContent>
			<xs:extension base="jsml-jsml">
				<xs:attribute name="parent" type="xs:string" />
				<xs:attribute name="top" type="xs:string" />
				<xs:attribute name="left" type="xs:string" />
				<xs:attribute name="right" type="xs:string" />
				<xs:attribute name="bottom" type="xs:string" />
				<xs:attribute name="width" type="xs:string" />
				<xs:attribute name="height" type="xs:string" />
				<xs:attribute name="min_width" type="xs:string" />
				<xs:attribute name="min_height" type="xs:string" />
				<xs:attribute name="max_width" type="xs:string" />
				<xs:attribute name="max_height" type="xs:string" />
				<xs:attribute name="unselectable" type="xs:boolean" />
				<xs:attribute name="visible" type="xs:boolean" />
				<xs:attribute name="visibility" type="visibility" />
				<xs:attribute name="disabled" type="xs:boolean" />
				<xs:attribute name="dock" type="jsml-dock" />
				<xs:attribute name="flow_clear" type="flow-clear"/>
				<xs:attribute name="margin" type="xs:string" />
				<xs:attribute name="border_width" type="xs:string" />
				<xs:attribute name="border_style" type="xs:string" />
				<xs:attribute name="border_color" type="xs:string" />
				<xs:attribute name="back_color" type="xs:string" />
				<xs:attribute name="text_color" type="xs:string" />
				<xs:attribute name="background" type="xs:string" />
				<xs:attribute name="text" type="xs:string" />
				<xs:attribute name="tooltip" type="xs:string" />
				<xs:attribute name="font" type="xs:string" />
				<xs:attribute name="font_size" type="xs:string" />
				<xs:attribute name="cursor" type="xs:string" />
				<xs:attribute name="opacity" type="xs:string" />
				<xs:attribute name="css_class" type="xs:string" />
				<xs:attribute name="css_text" type="xs:string" />
				<xs:attribute name="overflow" type="jsml-overflow"/>
				<xs:attribute name="overflow_x" type="jsml-overflow"/>
				<xs:attribute name="overflow_y" type="jsml-overflow"/>
				<xs:attribute name="horizontal_align" type="horizontal-align" />
				<xs:attribute name="vertical_align" type="vertical-align" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-simplecontrol">
		<xs:complexContent>
			<xs:extension base="jsml-control">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:group ref="class-member-group" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-complexcontrol">
		<xs:complexContent>
			<xs:extension base="jsml-control">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:group ref="class-member-group" />
					<xs:group ref="sub-element-group" />
				</xs:choice>
				<xs:attribute name="padding" type="xs:string" />
				<!--<xs:attribute name="zoom" type="zoom-mode" />-->
				<xs:attribute name="content_flow" type="content-flow" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="jsml-panel">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-groupbox">
		<xs:complexContent>
			<xs:extension base="jsml-panel">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!--<xs:complexType name="jsml-grid">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="row" type="jsml-row" />
				</xs:choice>
				<xs:attribute name="cell_border_width" type="xs:string" />
				<xs:attribute name="cell_border_style" type="xs:string" />
				<xs:attribute name="cell_border_color" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-row">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="cell" type="jsml-cell" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-cell">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>-->

	<xs:complexType name="jsml-jsmlelement">
		<xs:complexContent>
			<xs:extension base="jsml-simplecontrol">
				<xs:attribute name="zoom" type="zoom-mode" />
				<xs:attribute name="padding" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-htmlcontrol">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="html" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-image">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="src" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-label">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="text_align" type="horizontal-align" />
				<xs:attribute name="word_wrap" type="xs:boolean" />
				<xs:attribute name="font_size" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-textbox">
		<xs:complexContent>
			<xs:extension base="jsml-simplecontrol">
				<xs:attribute name="text_mode" type="text-mode" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-checkbox">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="checked" type="xs:boolean" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-dropdown">
		<xs:complexContent>
			<xs:extension base="jsml-simplecontrol">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="listitem" type="list-item"/>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:group name="class-member-group">
		<xs:choice>
			<xs:element name="jsml-ref">
				<xs:complexType>
					<xs:attribute name="jsml-enable" type="xs:boolean" />
					<xs:attribute name="name" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="constructor" type="jsml-constructor" />
			<xs:element name="initialize" type="jsml-initialize" />
			<xs:element name="method" type="jsml-method" />
			<xs:element name="attach" type="jsml-attach" />
			<xs:element name="xmldata" type="jsml-xmldata" />
			<xs:element name="property">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="get" type="jsml-propgetset" minOccurs="1" maxOccurs="1" />
						<xs:element name="set" type="jsml-propgetset" minOccurs="0" maxOccurs="1" />
					</xs:sequence>
					<xs:attribute name="name" type="jsml-var" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="sub-element-group">
		<xs:choice>
			<xs:element name="htmlcontrol" type="jsml-htmlcontrol" />
			<xs:element name="button" type="jsml-simplecontrol" />
			<xs:element name="image" type="jsml-image" />
			<xs:element name="label" type="jsml-label" />
			<xs:element name="textbox" type="jsml-textbox" />
			<xs:element name="dropdown" type="jsml-dropdown" />
			<xs:element name="checkbox" type="jsml-checkbox" />
			<xs:element name="panel" type="jsml-panel" />
			<xs:element name="groupbox" type="jsml-groupbox" />
			<!--<xs:element name="grid" type="jsml-grid" />-->
			<xs:element name="object">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="jsml-complexcontrol">
							<xs:attribute name="jsml-base" type="jsml-var" use="required" />
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="jsml-comment">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:any processContents="skip" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="jsml-block">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:group ref="sub-element-group" />
					</xs:choice>
					<xs:attribute name="jsml-enable" type="xs:boolean" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:element name="jsml">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group ref="sub-element-group" />
				<xs:element name="execute">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="jsml-enable" type="xs:boolean" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="include">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="jsml-enable" type="xs:boolean" />
								<xs:attribute name="src"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="jsml-def">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:group ref="class-member-group" />
							<xs:group ref="sub-element-group" />
						</xs:choice>
						<xs:attribute name="jsml-enable" type="xs:boolean" />
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ritesh9835/EmailServices/SendingEmailsWithWebMailInMVC/SendingEmailsWithWebMailInMVC/richtexteditor/dialogs/properties_style_layout.xml
<?xml version="1.0" encoding="utf-8" ?>
<jsml xmlns="http://cutesoft.net/jsml"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cutesoft.net/jsml ../core/jsml.xsd">

	<panel jsml-class="properties_text" dock="fill">
		<groupbox text="@LAYOUT" dock="top" overflow="visible" margin="4">
			<panel dock="left" width="180">
				<panel margin="7,3,1,3" height="18" dock="top">
					<label dock="left" vertical_align="middle" width="80" text="visibility:" text_align="right"/>
					<panel dock="left" width="4" />
					<panel dock="left" jsml-base="rtepropdropdown" propname="style:visibility" width="100">
						<listitem value="" text="@NOTSET" />
						<listitem value="visible" text="visible" />
						<listitem value="hidden" text="hidden" />
						<listitem value="collapse" text="collapse" />
						<listitem value="inherit" text="inherit" />
					</panel>
				</panel>
				<panel margin="7,3,1,3" height="18" dock="top">
					<label dock="left" vertical_align="middle" width="80" text="display:" text_align="right"/>
					<panel dock="left" width="4" />
					<panel dock="left" jsml-base="rtepropdropdown" propname="style:display" width="100">
						<listitem value="" text="@NOTSET" />
						<listitem value="none" text="none" />
						<listitem value="block" text="block" />
						<listitem value="inline" text="inline" />
						<listitem value="inline-block" text="inline-block" />
						<listitem value="inline-table" text="inline-table" />
						<listitem value="list-item" text="list-item" />
						<listitem value="table" text="table" />
						<listitem value="table-caption" text="table-caption" />
						<listitem value="table-cell" text="table-cell" />
						<listitem value="table-column	" text="table-column	" />
						<listitem value="table-row" text="table-row" />
						<listitem value="inherit" text="inherit" />
					</panel>
				</panel>
				<panel margin="7,3,1,3" height="18" dock="top">
					<label dock="left" vertical_align="middle" width="80" text="float:" text_align="right"/>
					<panel dock="left" width="4" />
					<panel dock="left" jsml-base="rtepropdropdown" propname="style:float" width="100">
						<listitem value="" text="@NOTSET" />
						<listitem value="none" text="none" />
						<listitem value="left" text="left" />
						<listitem value="right" text="right" />
						<listitem value="inherit" text="inherit" />
					</panel>
				</panel>
				<panel margin="7,3,1,3" height="18" dock="top">
					<label dock="left" vertical_align="middle" width="80" text="clear:" text_align="right"/>
					<panel dock="left" width="4" />
					<panel dock="left" jsml-base="rtepropdropdown" propname="style:clear" width="100">
						<listitem value="" text="@NOTSET" />
						<listitem value="none" text="none" />
						<listitem value="left" text="left" />
						<listitem value="right" text="right" />
						<listitem value="both" text="both" />
						<listitem value="inherit" text="inherit" />
					</panel>
				</panel>
				<panel margin="7,3,1,3" height="18" dock="top">
					<label dock="left" vertical_align="middle" width="80" text="cursor:" text_align="right"/>
					<panel dock="left" width="4" />
					<panel dock="left" jsml-base="rtepropdropdown" propname="style:cursor" width="100">
						<listitem value="" text="@NOTSET" />
						<listitem value="auto" text="auto" />
						<listitem value="pointer" text="pointer" />
						<listitem value="default" text="default" />
						<listitem value="text" text="text" />
						<listitem value="wait" text="wait" />
						<listitem value="move" text="move" />
						<listitem value="help" text="help" />
						<listitem value="crosshair" text="crosshair" />
						<listitem value="progress" text="progress" />
						<listitem value="e-resize" text="e-resize" />
						<listitem value="n-resize" text="n-resize" />
						<listitem value="ne-resize" text="ne-resize" />
						<listitem value="nw-resize" text="nw-resize" />
						<listitem value="s-resize" text="s-resize" />
						<listitem value="se-resize" text="se-resize" />
						<listitem value="sw-resize" text="sw-resize" />
						<listitem value="w-resize" text="w-resize" />
					</panel>
				</panel>
			</panel>
			<panel dock="left" width="200">
				<panel margin="7,3,1,3" height="18" dock="top">
					<label dock="left" vertical_align="middle" width="80" text="overflow:" text_align="right"/>
					<panel dock="left" width="4" />
					<panel dock="left" jsml-base="rtepropdropdown" propname="style:overflow" width="100">
						<listitem value="" text="@NOTSET" />
						<listitem value="visible" text="visible" />
						<listitem value="hidden" text="hidden" />
						<listitem value="scroll" text="scroll" />
						<listitem value="auto" text="auto" />
						<listitem value="inherit" text="inherit" />
					</panel>
				</panel>
				<panel margin="7,3,1,3" height="18" dock="top">
					<label dock="left" vertical_align="middle" width="80" text="clip:" text_align="right"/>
					<panel dock="left" width="4" />
					<label dock="left" vertical_align="middle" width="100" text="rect(...)"/>
				</panel>
				<panel margin="7,3,1,3" height="18" dock="top">
					<label dock="left" vertical_align="middle" width="80" text="top:" text_align="right"/>
					<panel dock="left" width="4" />
					<panel dock="left" jsml-base="rtepropnumupdown" width="100" propname="style:clip" suffix="px" jsml-local="cliptop">
						<method name="set_node_value">
							instance.set_clip_value(0,value);
						</method>
						<method name="get_node_value">
							return instance.get_clip_value(0);
						</method>
					</panel>
				</panel>
				<panel margin="7,3,1,3" height="18" dock="top">
					<label dock="left" vertical_align="middle" width="80" text="right:" text_align="right"/>
					<panel dock="left" width="4" />
					<panel dock="left" jsml-base="rtepropnumupdown" width="100" propname="style:clip" suffix="px" jsml-local="clipright">
						<method name="set_node_value">
							instance.set_clip_value(1,value);
						</method>
						<method name="get_node_value">
							return instance.get_clip_value(1);
						</method>
					</panel>
				</panel>
				<panel margin="7,3,1,3" height="18" dock="top">
					<label dock="left" vertical_align="middle" width="80" text="bottom:" text_align="right"/>
					<panel dock="left" width="4" />
					<panel dock="left" jsml-base="rtepropnumupdown" width="100" propname="style:clip" suffix="px" jsml-local="clipbottom">
						<method name="set_node_value">
							instance.set_clip_value(2,value);
						</method>
						<method name="get_node_value">
							return instance.get_clip_value(2);
						</method>
					</panel>
				</panel>
				<panel margin="7,3,1,3" height="18" dock="top">
					<label dock="left" vertical_align="middle" width="80" text="left:" text_align="right"/>
					<panel dock="left" width="4" />
					<panel dock="left" jsml-base="rtepropnumupdown" width="100" propname="style:clip" suffix="px" jsml-local="clipleft">
						<method name="set_node_value">
							instance.set_clip_value(3,value);
						</method>
						<method name="get_node_value">
							return instance.get_clip_value(3);
						</method>
					</panel>
				</panel>
				<panel margin="7,3,30,3" height="18" dock="top">
				</panel>
			</panel>
		</groupbox>

		<method name="find_node">
			<![CDATA[
			for(var p=self;p&&p.get_parent;p=p.get_parent())
				if(p._rtenode)
					return p._rtenode;
			]]>
		</method>
		<method name="get_clip_value" arguments="index">
			<![CDATA[
			var node=self.find_node();
			var clip=node.GetStyle("clip");
			if(!clip)return null;
			return clip.replace(/.*rect\((.*)\s(.*)\s(.*)\s(.*)\).*/g,"$"+(index+1))
			]]>
		</method>
		<method name="set_clip_value" arguments="index,value">
			<![CDATA[
			var node=self.find_node();
			var clip=node.GetStyle("clip");
			if(!clip&&!value)return;
			clip=(clip||"").replace(/.*rect\((.*)\s(.*)\s(.*)\s(.*)\).*/g,"$1,$2,$3,$4").split(",");
			if(clip.length!=4)clip=["0px","0px","0px","0px"];
			clip[index]=value;
			clip=clip.join(" ");
			if(clip=="0px 0px 0px 0px")
				clip=null;
			else
				clip="rect("+clip+")";
			node.SetStyle("clip",clip);
			]]>
		</method>
	</panel>
	<panel jsml-base="properties_text" />
</jsml>
