=== ritesh9835/EmailServices/SendingEmailsWithWebMailInMVC/SendingEmailsWithWebMailInMVC/richtexteditor/core/jsml.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="jsml" targetNamespace="http://cutesoft.net/jsml" elementFormDefault="qualified" xmlns="http://cutesoft.net/jsml" xmlns:mstns="http://cutesoft.net/jsml" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="jsml-var">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^=]?[0-9a-zA-Z_${}]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="jsml-var-list">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^=]?[0-9a-zA-Z_${},]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="visibility">
		<xs:restriction base="xs:string">
			<xs:enumeration value="visible" />
			<xs:enumeration value="hidden" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="jsml-dock">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top" />
			<xs:enumeration value="left" />
			<xs:enumeration value="right" />
			<xs:enumeration value="bottom" />
			<xs:enumeration value="fill" />
			<xs:enumeration value="over" />
			<xs:enumeration value="flow" />
			<xs:enumeration value="none" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="content-flow">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left" />
			<xs:enumeration value="right" />
			<xs:enumeration value="bottomleft" />
			<xs:enumeration value="bottomright" />
			<xs:enumeration value="uptoleft" />
			<xs:enumeration value="downtoleft" />
			<xs:enumeration value="uptoright" />
			<xs:enumeration value="downtoright" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="flow-clear">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none" />
			<xs:enumeration value="both" />
			<xs:enumeration value="prev" />
			<xs:enumeration value="next" />
			<xs:enumeration value="follow" />
			<xs:enumeration value="newline" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="jsml-overflow">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none" />
			<xs:enumeration value="visible" />
			<xs:enumeration value="scroll" />
			<xs:enumeration value="default" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="zoom-mode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none" />
			<xs:enumeration value="both" />
			<xs:enumeration value="in" />
			<xs:enumeration value="out" />
			<xs:pattern value="(none)|(both)|(in)|(out)|([0-9%\.]+)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="vertical-align">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top" />
			<xs:enumeration value="middle" />
			<xs:enumeration value="bottom" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="horizontal-align">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left" />
			<xs:enumeration value="center" />
			<xs:enumeration value="right" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="text-mode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="singleline" />
			<xs:enumeration value="multipleline" />
			<xs:enumeration value="password" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="jsml-xmldata" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:any />
		</xs:choice>
		<xs:attribute name="rawhtml" type="xs:boolean" />
	</xs:complexType>
	<xs:complexType name="jsml-constructor">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="arguments" type="jsml-var-list" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-initialize">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-method">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="name" type="jsml-var" use="required" />
				<xs:attribute name="arguments" type="jsml-var-list" />
				<xs:attribute name="overrideas" type="jsml-var" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-attach">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="name" type="jsml-var-list" use="required" />
				<xs:attribute name="arguments" type="jsml-var-list" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-propgetset">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="arguments" type="jsml-var-list" />
				<xs:attribute name="overrideas" type="jsml-var" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="list-item">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="jsml-enable" type="xs:boolean" />
				<xs:attribute name="value" type="xs:string" />
				<xs:attribute name="text" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="jsml-jsml">
		<xs:attribute name="jsml-enable" type="xs:boolean" />
		<xs:attribute name="jsml-append" type="xs:boolean" />
		<xs:attribute name="jsml-class" type="jsml-var" />
		<xs:attribute name="jsml-base" type="jsml-var" />
		<xs:attribute name="jsml-local" type="jsml-var" />
		<xs:attribute name="jsml-member" type="jsml-var" />
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="var" type="jsml-var" />
		<xs:attribute name="vars" type="jsml-var-list" />
		<xs:anyAttribute />
	</xs:complexType>
	<xs:complexType name="jsml-control">
		<xs:complexContent>
			<xs:extension base="jsml-jsml">
				<xs:attribute name="parent" type="xs:string" />
				<xs:attribute name="top" type="xs:string" />
				<xs:attribute name="left" type="xs:string" />
				<xs:attribute name="right" type="xs:string" />
				<xs:attribute name="bottom" type="xs:string" />
				<xs:attribute name="width" type="xs:string" />
				<xs:attribute name="height" type="xs:string" />
				<xs:attribute name="min_width" type="xs:string" />
				<xs:attribute name="min_height" type="xs:string" />
				<xs:attribute name="max_width" type="xs:string" />
				<xs:attribute name="max_height" type="xs:string" />
				<xs:attribute name="unselectable" type="xs:boolean" />
				<xs:attribute name="visible" type="xs:boolean" />
				<xs:attribute name="visibility" type="visibility" />
				<xs:attribute name="disabled" type="xs:boolean" />
				<xs:attribute name="dock" type="jsml-dock" />
				<xs:attribute name="flow_clear" type="flow-clear"/>
				<xs:attribute name="margin" type="xs:string" />
				<xs:attribute name="border_width" type="xs:string" />
				<xs:attribute name="border_style" type="xs:string" />
				<xs:attribute name="border_color" type="xs:string" />
				<xs:attribute name="back_color" type="xs:string" />
				<xs:attribute name="text_color" type="xs:string" />
				<xs:attribute name="background" type="xs:string" />
				<xs:attribute name="text" type="xs:string" />
				<xs:attribute name="tooltip" type="xs:string" />
				<xs:attribute name="font" type="xs:string" />
				<xs:attribute name="font_size" type="xs:string" />
				<xs:attribute name="cursor" type="xs:string" />
				<xs:attribute name="opacity" type="xs:string" />
				<xs:attribute name="css_class" type="xs:string" />
				<xs:attribute name="css_text" type="xs:string" />
				<xs:attribute name="overflow" type="jsml-overflow"/>
				<xs:attribute name="overflow_x" type="jsml-overflow"/>
				<xs:attribute name="overflow_y" type="jsml-overflow"/>
				<xs:attribute name="horizontal_align" type="horizontal-align" />
				<xs:attribute name="vertical_align" type="vertical-align" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-simplecontrol">
		<xs:complexContent>
			<xs:extension base="jsml-control">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:group ref="class-member-group" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-complexcontrol">
		<xs:complexContent>
			<xs:extension base="jsml-control">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:group ref="class-member-group" />
					<xs:group ref="sub-element-group" />
				</xs:choice>
				<xs:attribute name="padding" type="xs:string" />
				<!--<xs:attribute name="zoom" type="zoom-mode" />-->
				<xs:attribute name="content_flow" type="content-flow" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="jsml-panel">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-groupbox">
		<xs:complexContent>
			<xs:extension base="jsml-panel">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!--<xs:complexType name="jsml-grid">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="row" type="jsml-row" />
				</xs:choice>
				<xs:attribute name="cell_border_width" type="xs:string" />
				<xs:attribute name="cell_border_style" type="xs:string" />
				<xs:attribute name="cell_border_color" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-row">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="cell" type="jsml-cell" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-cell">
		<xs:complexContent>
			<xs:extension base="jsml-complexcontrol">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>-->

	<xs:complexType name="jsml-jsmlelement">
		<xs:complexContent>
			<xs:extension base="jsml-simplecontrol">
				<xs:attribute name="zoom" type="zoom-mode" />
				<xs:attribute name="padding" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-htmlcontrol">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="html" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-image">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="src" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-label">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="text_align" type="horizontal-align" />
				<xs:attribute name="word_wrap" type="xs:boolean" />
				<xs:attribute name="font_size" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-textbox">
		<xs:complexContent>
			<xs:extension base="jsml-simplecontrol">
				<xs:attribute name="text_mode" type="text-mode" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-checkbox">
		<xs:complexContent>
			<xs:extension base="jsml-jsmlelement">
				<xs:attribute name="checked" type="xs:boolean" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jsml-dropdown">
		<xs:complexContent>
			<xs:extension base="jsml-simplecontrol">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="listitem" type="list-item"/>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:group name="class-member-group">
		<xs:choice>
			<xs:element name="jsml-ref">
				<xs:complexType>
					<xs:attribute name="jsml-enable" type="xs:boolean" />
					<xs:attribute name="name" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="constructor" type="jsml-constructor" />
			<xs:element name="initialize" type="jsml-initialize" />
			<xs:element name="method" type="jsml-method" />
			<xs:element name="attach" type="jsml-attach" />
			<xs:element name="xmldata" type="jsml-xmldata" />
			<xs:element name="property">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="get" type="jsml-propgetset" minOccurs="1" maxOccurs="1" />
						<xs:element name="set" type="jsml-propgetset" minOccurs="0" maxOccurs="1" />
					</xs:sequence>
					<xs:attribute name="name" type="jsml-var" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="sub-element-group">
		<xs:choice>
			<xs:element name="htmlcontrol" type="jsml-htmlcontrol" />
			<xs:element name="button" type="jsml-simplecontrol" />
			<xs:element name="image" type="jsml-image" />
			<xs:element name="label" type="jsml-label" />
			<xs:element name="textbox" type="jsml-textbox" />
			<xs:element name="dropdown" type="jsml-dropdown" />
			<xs:element name="checkbox" type="jsml-checkbox" />
			<xs:element name="panel" type="jsml-panel" />
			<xs:element name="groupbox" type="jsml-groupbox" />
			<!--<xs:element name="grid" type="jsml-grid" />-->
			<xs:element name="object">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="jsml-complexcontrol">
							<xs:attribute name="jsml-base" type="jsml-var" use="required" />
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="jsml-comment">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:any processContents="skip" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="jsml-block">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:group ref="sub-element-group" />
					</xs:choice>
					<xs:attribute name="jsml-enable" type="xs:boolean" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:element name="jsml">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group ref="sub-element-group" />
				<xs:element name="execute">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="jsml-enable" type="xs:boolean" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="include">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="jsml-enable" type="xs:boolean" />
								<xs:attribute name="src"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="jsml-def">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:group ref="class-member-group" />
							<xs:group ref="sub-element-group" />
						</xs:choice>
						<xs:attribute name="jsml-enable" type="xs:boolean" />
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ritesh9835/EmailServices/SendingEmailsWithWebMailInMVC/SendingEmailsWithWebMailInMVC/richtexteditor/dialogs/insertimagemap.xml
<?xml version="1.0" encoding="utf-8" ?>
<jsml xmlns="http://cutesoft.net/jsml"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cutesoft.net/jsml ../core/jsml.xsd">

	<execute>
		dialog.set_back_color("#F9F9F9");
		dialog.set_title(editor.GetLangText("INSERTIMAGEMAP"));
	</execute>

	<panel jsml-class="insertimagemap_area" width="32" height="32">
		<panel dock="top" jsml-local="resizet" height="2" back_color="blue" margin="0,2,0,0"/>
		<panel dock="left" jsml-local="resizel" width="2" back_color="blue" margin="0,0,2,0"/>

		<panel dock="right" width="6" cursor="e-resize" vertical_align="middle">
			<panel dock="bottom" height="2" jsml-local="resizez" back_color="blue" margin="0,2,2,0" cursor="se-resize">
				<attach name="mousedown" arguments="je,de">
					de.cancel();
					instance.resizearea(de,1,1);
				</attach>
			</panel>
			<panel dock="left" back_color="yellow" opacity="50" width="2" />
			<panel dock="fill" jsml-local="resizex" width="2" back_color="blue" margin="0,2,0,0" />
			<image jsml-local="dotr" width="6" height="6" zoom="both" src="{folder}dialogs/images/dot_ring.png" overflow="none" />
			<attach name="mousedown" arguments="je,de">
				instance.resizearea(de,1,0);
			</attach>
		</panel>
		<panel dock="bottom" height="6" cursor="n-resize" horizontal_align="center">
			<panel dock="top" back_color="yellow" opacity="50" height="2" />
			<panel dock="fill" jsml-local="resizey" back_color="blue" margin="0,0,2,0" />
			<image jsml-local="dotb" width="6" height="6" zoom="both" src="{folder}dialogs/images/dot_ring.png" overflow="none" />
			<attach name="mousedown" arguments="je,de">
				instance.resizearea(de,0,1);
			</attach>
		</panel>
		<panel dock="fill" back_color="yellow" opacity="50">
			<attach name="mousedown" arguments="je,de">
				<![CDATA[
				de.cancel();
				if(self.lastdowntime)
				{
					if(new Date().getTime()-self.lastdowntime<300)
					{
						self.bubble_event("dblclickarea",instance._area)
						return;
					}
				}
				instance.dialoginst.SelectHotSpot(instance._area);
				instance.start_move_offset(de,function()
				{
					instance.updatecoords();
				});
				self.lastdowntime=new Date().getTime();
				]]>
			</attach>
		</panel>

		<initialize>
			//self._estyle.boxShadow="2px 2px 2px #333333";
		</initialize>
		<property name="area">
			<get>
				return self._area;
			</get>
			<set>
				self._area=value;
				var coords=self._area.GetAttribute("coords")||"";
				coords=coords.split(',');
				var x1=parseInt(coords[0])||0;
				var y1=parseInt(coords[1])||0;
				var x2=parseInt(coords[2])||0;
				var y2=parseInt(coords[3])||0;
				self.set_left(x1);
				self.set_top(y1);
				self.set_width( (x2-x1)||32 );
				self.set_height( (y2-y1)||32 );
				self.set_offset_x(0);
				self.set_offset_y(0);
			</set>
		</property>
		<property name="selected">
			<get>
				return self._selected;
			</get>
			<set>
				self._selected=value;
				var color=value?"red":"blue";
				self.set_border_color(color);
				resizex.set_back_color(color);
				resizey.set_back_color(color);
				resizez.set_back_color(color);
				resizet.set_back_color(color);
				resizel.set_back_color(color);
			</set>
		</property>
		<method name="updatecoords">
			var x1=self.get_offset_x()+self.get_left();
			var y1=self.get_offset_y()+self.get_top();
			var x2=x1+self.get_width();
			var y2=y1+self.get_height();
			var coords=x1+","+y1+","+x2+","+y2;
			self._area.SetAttribute("coords",coords);
		</method>
		<method name="resizearea" arguments="de,fr,fb">
			<![CDATA[
			self.start_resize(de,0,fr,fb,0,12,function()
			{
				self.updatecoords();
			});
			]]>
		</method>
		<attach name="mousehover">
			var alt=self._area.GetAttribute("alt");
			var url=self._area.GetAttribute("href");
			var sb=[];
			if(alt)sb.push(alt);
			if(url)sb.push(url);
			self.set_tooltip(sb.join("\r\n"));
		</attach>

	</panel>

	<panel jsml-class="insertimagemap_dialog" dock="fill" overflow="visible" padding="5">

		<panel dock="top" overflow="visible" text="@INSERTIMAGEMAP" width="180" jsml-local="mappanel">

			<panel dock="top" margin="2" padding="2" height="24">
				<label dock="left" width="80" text="@MAPNAME|:" vertical_align="middle" />
				<panel dock="left" width="130"  jsml-base="rteproptextbox" propname="name" />
				<panel dock="left" width="15"/>

				<image jsml-base="imagebutton" imagename="imagemap" tooltip="@ADDHOTSPOT" width="20" height="20" dock="left" margin="0,2,0,2">
					<attach name="click">
						instance.InsertHotSpot();
					</attach>
				</image>
				<image jsml-base="imagebutton" imagename="link" jsml-local="btnedit" disabled="true" tooltip="@EDITHOTSPOT" width="20" height="20" dock="left" margin="0,2,0,2">
					<attach name="click">
						instance.ShowHotSpotDialog();
					</attach>
				</image>
				<image jsml-base="imagebutton" imagename="delete" jsml-local="btndel" disabled="true" tooltip="@DELETEHOTSPOT" width="20" height="20" dock="left" margin="0,2,0,2">
					<attach name="click">
						instance.DeleteHotSpot();
					</attach>
				</image>
			</panel>

		</panel>

		<panel dock="bottom" margin="3" padding="6" overflow="visible">

			<panel dock="right" margin="3" overflow="visible">
				<initialize>
					if(!option.nestedmode)self.set_visible(false);
				</initialize>
				<button dock="left" width="82" height="24"  text="@CLOSE">
					<attach name="click">
						dialog.close();
					</attach>
				</button>
			</panel>

			<panel dock="right" margin="3" overflow="visible">
				<initialize>
					if(option.nestedmode)self.set_visible(false);
				</initialize>
				<button dock="left" width="82" height="24"  text="@OK" margin="0,12,0,0">
					<initialize>
						if(option.oktext)self.set_text(option.oktext);
					</initialize>
					<attach name="click">
						var name=option.targetnode.GetAttribute("name");
						if(!name)return;
						var oldid=option.targetnode.GetAttribute("id");
						if(oldid!=name)option.targetnode.SetAttribute("id",name);
						option.targetimg.SetAttribute("usemap","#"+name);
						dialog.result=true;
						dialog.close();
					</attach>
				</button>
				<button dock="left" width="82" height="24"  text="@CANCEL">
					<attach name="click">
						dialog.close();
					</attach>
				</button>
			</panel>

		</panel>

		<panel dock="fill">
			<panel dock="fill" jsml-local="areapanel" overflow="scroll" margin="3" padding="3" border_width="1" border_style="inset">
				<image zoom="none">
					<initialize>
						self.set_src(option.targetimg.GetAttribute("src"));
						var w=parseInt(option.targetimg.GetStyle("width"));
						var h=parseInt(option.targetimg.GetStyle("height"));
						//document.title=[w,h];
						if(w)self.set_width(w);
						if(h)self.set_height(h);
						if(w||h)self.set_overflow("none");
					</initialize>
				</image>
			</panel>
		</panel>

		<initialize>
			<![CDATA[
			mappanel._rtenode=option.targetnode;
			var c=option.targetnode.GetChildCount();
			for(var i=0;i<c;i++)
			{
				var child=option.targetnode.GetChildAt(i);
				if(child.GetNameLower()!="area")
					continue;
				self.ShowHotSpot(child);
			}
			]]>
		</initialize>
		<method name="InsertHotSpot">
			<![CDATA[
			var area=new $rte.DataElement("area");
			area.SetAttribute("shape","rect");
			area.SetAttribute("coords","0,0,32,32");
			option.targetnode.AppendChild(area);
			self.ShowHotSpot(area);
			self.SelectHotSpot(area);
			self.ShowHotSpotDialog();
			]]>
		</method>
		<attach name="dblclickarea">
			self.ShowHotSpotDialog();
		</attach>
		<method name="ShowHotSpotDialog">
			<![CDATA[
			var tag=self._selectedarea;
			if(!tag)return;
			var newoption={width:430,height:170,targetnode:tag};
			newoption.nestedmode=true;
			editor.ShowXmlDialog(editor.BuildDialogUrl("insertimagemaplink.xml"),newoption);
			]]>
		</method>
		<method name="ShowHotSpot">
			<![CDATA[
			var ctrl=jsml.class_create_instance("insertimagemap_area");
			ctrl.dialoginst=self;
			ctrl.set_area(value);
			areapanel.append_child(ctrl);
			]]>
		</method>
		<method name="SelectHotSpot" arguments="area">
			<![CDATA[
			self._selectedarea=area;
			self.invoke_event("selectedareachanged");
			//hotspotpanel._rtenode=area;
			//hotspotpanel.set_visible(true);
			//hotspotpanel.invoke_recursive("loadvalue");
			for(var i=1;i<areapanel._childs.length;i++)
			{
				var ctrl=areapanel._childs[i];
				if(ctrl.get_area()==area)
					ctrl.set_selected(true);
				else
					ctrl.set_selected(false);
			}
			]]>
		</method>
		<method name="DeleteHotSpot">
			<![CDATA[
			if(!confirm(editor.GetLangText("confirm_deleteitem")))
				return;
			var area=self._selectedarea;
			self._selectedarea=null;
			self.invoke_event("selectedareachanged");
			//hotspotpanel._rtenode=null;
			//hotspotpanel.set_visible(false);
			for(var i=1;i<areapanel._childs.length;i++)
			{
				var ctrl=areapanel._childs[i];
				if(ctrl.get_area()==area)
				{
					ctrl.dispose();
					break;
				}
			}
			area.RemoveNode();
			]]>
		</method>
		<attach name="selectedareachanged">
			var v=!self._selectedarea;
			btnedit.set_disabled(v);
			btndel.set_disabled(v);
		</attach>

	</panel>

	<panel jsml-base="insertimagemap_dialog" />


</jsml>
